### ISSUE TITLE
Questions for meeting 18/05

### ISSUE THREAD

**Issue by katbow** [FAC7/SharePlan#48]
1. Templates for text messages
2. Wireframes
3. User stories (narratives) would be super useful
   1.Ask for some info to our readme. (purpose/description/goal)
4. Letter format? - how does he wish to upload them?
5. What does he mean by 'asking us to link stakeholder mobile or email'
6. ask whether there is a data structure for the API CareNotes  
   1.can a letter have multiple recipients  
7. what is the difference between recipients and stakeholders  
8. do we want the whole login/auth

**Comment by katbow** [comment]
Answers to email Qs
- What are the features of your app that you would like? It would be great if you could list them in priority order?  
- Could you prepare some style guidance? Think of how you want it to look. 
- We remember that you had an API? What was the API specifically for?  Access to it would help us with our data structure. 
- Could you possibly think about example user stories: think of your experience and the clients experience.  What are the scenarios when the app would be used. 
- Finally, do you have a Github account?  If you do, we can invite you to join and look at the repository we are working on.
1. Answers to general Qs
   - In terms of features- be able to link a report with a particular patient
   - Change the status of the report (On the list, In preparation, Waiting review, Sent) or something like that
   - Notification to the client and other stakeholders of changes in status.
   - Links to stakeholders email or mobile numbers
   - When the report is ‘waiting for review’ that it is available in a ‘dropbox’ where patients or stakeholders who are assigned editing rights can edit a version of the document
   - That changes in the document are tracked
   - That this links with our electronic record system so that all new information points are recorded  
2. I liked the style you guys had already developed. We can talk about that a bit further in person.
3. The API would be for CareNotes- I will ask my IM&T people but they won’t just give it out.
   I have a meeting scheduled with them next Wednesday- could one of you join at 12-1. Address below. Maybe Dan should be there also?
4. lots of stories available to tell….
5. What is Github?? Do invite me please.

**Comment by Virginie-T** [comment]
Emilios answers:
- Templates for text messages (what do you want the messages to say?)
  Hi.  Each team that uses these may have a different message they want to say depending on the nature of the report.  It would be helpful if this was user defined/editable.
  Some examples for Daryl’s team would be
  Hello.  This is a message from the Tavistock and Portman SharePlan.  Your report has been placed on the pending list and will be attended to shortly.
  Hello.  This is a message from the Tavistock and Portman SharePlan.  Your report has been placed on the ‘in progress’ list.  We will be contacting you next when the report is ready to edit/send.
  Hello.  This is a message from the Tavistock and Portman SharePlan.  Your report has been sent to …   …  …
- Style Guide (what colours, fonts, look and feel,... would you like?)
  Daryl- have you got a view- I liked the colours you chose in the initial Pidgeon version.
- Letter format? - how do you wish to upload them? (would be preferable in pdf)
  Daryl- what do you think??
- Can a letter have multiple recipients
  Yes please
- What is the difference between recipients and stakeholders?
  Nothing really.  The main stakeholders are the person using SharePlan clinically- either an administrator or Clinician. And then the patients.  Recipients would be people the patient has agreed to receive a copy of the letter and who may also wish to receive notifications.

**Comment by Virginie-T** [comment]
Daryl's answer:

Hey all,
Please see my comments below:
Templates for text messages (what do you want the messages to say?)
·         SharePlan has received a new notification, please log in to view.

I would use this template as we don’t really want to publish the name Tavistock into text messages due to some patients not wanting relatives or friends knowing they attend. I reckon after they have logged in the system, a notification should tell them what change we have made i.e. Your appointment letter is ready to view or Your report has currently been uploaded and is currently pending. I don’t think this should be texted though, I think it should only be notified once logged in?

Style Guide (what colours, fonts, look and feel,... would you like?)
·         I feel I could leave this down to you guys as you have blended the colors greatly already. I say go with the pigeon colors.

User Stories
·         Could you explain in abit more depth what you mean by user story?

Think about info to add to the readme. (purpose/description/goal)
·         Could you explain in abit more depth what you mean by this?

Letter format? - how do you wish to upload them? (would be preferable in PDF)
I believe when using this type of program all documents should be uploaded as PDF however they should have features to the upload; such as:
·         Having a main account administrator for each team to rectify uploaded errors.

·         Letting the main account administrator have the power of applying restricted access to service users and their contacts so that content may only be viewed by who we choose, same applies to notes added.

·         I don’t think clinicians should be uploading any of their own drafted content; it should go through the main account holder, clinicians should email the documents to the account holder for that team, and then they decide at what point the document should be uploaded, the reason for this is: the status bar would not work for GP, appointment or reminder letters as we finalise these before we upload them here, the status bar would only really work on report status’ as this is a lengthy process.

·         We would also need to implement an audit trail for uploading files so that we can record who is uploading and at what time and to also record any additional changes.

Can a letter have multiple recipients
·         Yes – however this options will need to have an enabled feature where we can tick whether or not we want to involve them into a particular letter.

What is the difference between recipients and stakeholders?
·         Please change the title stakeholders over to correspondence – I believe it is much more user friendly

Please note:       On my long painful journey home stuffed with pizza, I had a thought… have you guys thought about how we would deal with a situation where one of the service users writes on a documents? How would that notify the team? Who would it notify? And how quick? I think this needs to be built in as if someone writes something and we don’t respond or miss it completely it could have mass impacts on us. I also think it should notify only 1 team member i.e. the main account administrator.
I also thought about the account administrator having overall access i.e. adding clinicians to use this program, adding patients to clinicians list/caseloads as well as removing them, being able to add confidential credentials on the service users page etc.
Do get back to me to let me know what you guys think!
Best wishes,
Daryl
